server:
  port: 8082

spring:
  application:
    name: authorization-service
  main:
    allow-circular-references: true
  cloud:
    compatibility-verifier:
      enabled: false
  # data:
  #   mongodb:
  #     host: localhost
  #     port: 27017
  #     database: authorization_service_db
  data:
    mongodb:
      uri: mongodb+srv://lhagvabatulzii:Lhagv%401592@authentication.cyi8i.mongodb.net/authorization_service_db?retryWrites=true&w=majority&appName=Authentication&ssl=true&tls=true&authSource=admin&maxPoolSize=50&minPoolSize=5
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 