server:
  port: 8082

spring:
  application:
    name: authorization-service
  main:
    allow-circular-references: true
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authorization_service_db

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 